dist: trusty

language: node_js
node_js:
  - '4'
  - '6'
  - '7'
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - if [[ `npm -v` == 2* ]]; then npm i -g npm@latest; fi

install:
  - npm prune
  - npm install

notifications:
  email: false
